spring:
  application:
    name: Fone-Hub
  datasource:
    url: jdbc:mysql://localhost:3306/fone_hub?createDatabaseIfNotExist=true
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/

application:
  cloudinary:
    cloud-name: fonehub
    api-key: 676181334112719
    api-secret: IKOOBcTyHL_uEaWaOvYwAeJajOY
